# Generated by Django 4.0.3 on 2022-11-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('sub_category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_address', models.CharField(max_length=100)),
                ('res_road_address', models.CharField(max_length=100)),
                ('res_tel', models.CharField(blank=True, max_length=30, null=True)),
                ('res_link', models.URLField(blank=True, null=True)),
                ('res_stars', models.FloatField(blank=True, null=True)),
                ('res_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('res_description', models.TextField(blank=True, null=True)),
                ('res_find', models.CharField(blank=True, max_length=200, null=True)),
                ('res_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('res_comfortables', models.CharField(blank=True, max_length=200, null=True)),
                ('res_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/restaurant')),
                ('res_sub_thumbnail1', models.ImageField(blank=True, null=True, upload_to='images/restaurant')),
                ('res_sub_thumbnail2', models.ImageField(blank=True, null=True, upload_to='images/restaurant')),
                ('res_sub_thumbnail3', models.ImageField(blank=True, null=True, upload_to='images/restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.TextField(null=True)),
                ('site_id', models.IntegerField(unique=True)),
                ('store_name', models.TextField(null=True)),
                ('micro_review', models.TextField(null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('main_image_url', models.TextField(null=True)),
                ('tel', models.TextField()),
                ('thumbnail', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('road_address', models.TextField(null=True)),
                ('abbr_address', models.TextField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('visit_review_count', models.IntegerField(null=True)),
                ('blog_review_count', models.IntegerField(null=True)),
                ('biz_hour_info', models.TextField(null=True)),
                ('create_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_name', models.TextField(null=True)),
                ('menu_price', models.IntegerField(null=True)),
                ('menu_image', models.TextField(null=True)),
                ('menu_desc', models.TextField(null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.store', to_field='site_id')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.JSONField(null=True)),
                ('menu_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='place.restaurant')),
            ],
        ),
    ]
